name: CI/CD Deploy

on:
  push:
    branches: [ main ] # Trigger on push to main branch
  workflow_dispatch:

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout code
          uses: actions/checkout@v4
            
        - name: Copy docker-compose.yml via SSH
          uses: appleboy/scp-action@master
          with:
            host: ${{ secrets.SSH_HOST_FELIX }}
            username: ${{ secrets.SSH_USER_FELIX }}
            key: ${{ secrets.SSH_PRIVATE_KEY_FELIX }}
            source: "./docker-compose.yml"
            target: "/home/deployer/hackfest"

        - name: Deploy to VPS via SSH
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.SSH_HOST_FELIX }}
            username: ${{ secrets.SSH_USER_FELIX }}
            key: ${{ secrets.SSH_PRIVATE_KEY_FELIX }}
            script: |
              cd /home/deployer/hackfest
              git pull
              
              # Restart containers with the new image
              docker compose up -d
              
              # Optional: Clean up old images to save disk space
              docker image prune -f